### ISSUE TITLE
Rename this DSL

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/air-script#1]
We need to come up with a new name for this DSL that will ideally tick these boxes:

1. not in use
2. easy to pronounce
3. distinct enough to search for
4. no negative connotations

**Comment by bobbinth** [comment]
I think points 1 and 3 are nice to have but not required as we are not thinking of this as a standalone product.

**Comment by tohrnii** [comment]
I liked @bobbinth's earlier suggestion, "abacus".

**Comment by grjte** [comment]
Alright, let's use Abacus! (Unless there are any final thoughts.) We can update all references as part of the v0.1 release this week.

**Comment by bobbinth** [comment]
One other option is to use "Air" in the name somehow. One option that comes to mind is "AirScript" (I've used this before, but that language is not maintained any more) - but there could be other options as well. So, if people prefer "AirScript" to "Abacus", I'm fine with that.

**Comment by tohrnii** [comment]
Sorry, I created a duplicate issue #59 for changing references to Air DSL.

**Comment by tohrnii** [comment]
Another suggestion by @bobbinth:
> Thought for the future: I wonder if we should rename the executable to just `air` instead of `air-script`.

**Comment by grjte** [comment]
I agree about not using `air-script` for the executable name. We could also use `airc` as in "air compiler"

**Comment by bobbinth** [comment]
I like `airc`!

**Comment by bobbinth** [comment]
Closed by #62 and #69.
