### ISSUE TITLE
merge boundary constraints into AlgebraicGraph and support variables

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-script#106]
Variable support to transition constraint was added in #100. We should also add support for variables to boundary constraints. It might be useful to also add boundary constraints to the constraints graph in the same PR we add the variables.

The original issue with syntax is described in #61.

**Comment by grjte** [comment]
It now looks like we should do this task before completing #56, since having the boundary constraints in the constraints graph will simplify GCE generation a lot

**Comment by grjte** [comment]
Closed by #116 #117 #126 and #160
