### ISSUE TITLE
Update the CLI to specify the target output type

### ISSUE THREAD

**Issue by Overcastan** [0xPolygonMiden/air-script#107]
Originally written by @grjte in this [discussion](https://github.com/0xPolygonMiden/air-script/pull/104#discussion_r1052400995):

> Now that we have multiple codegen options, we should update the CLI to accept another input that specifies the target output type.

**Comment by bobbinth** [comment]
Closing this as it has already been implemented. We currently can output either Winterfell Rust code or MASM.
