### ISSUE TITLE
unroll exponentiation into multiplications in winter codegen

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/air-script#130]
We should remember that using `exp` could be quite expensive as it uses constant-time exponentiation. In the future, we might want o "unroll" this into a sequence of multiplications.

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/air-script/pull/126#discussion_r1090953576_

**Comment by bobbinth** [comment]
Superseded by #333.
