### ISSUE TITLE
Allow to access a vector from a matrix

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-script#132]
Trying to access a vector from a matrix results in some problems currently. The parser recognizes it incorrectly and the error thrown at the IR level is incorrect. We should be able to support statements like these:

```
let a = [[1, 2], [3, 4]]
let b = a[0]
```

This should also be handled for list comprehension.

@grjte raised this point in an earlier PR review but it was left unaddressed.

**Comment by grjte** [comment]
Closed by #147
