### ISSUE TITLE
Figure out a way to handle whitespaces more strictly

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-script#146]
Currently, the following statements are equivalent:
```
let x = a[0]
```
```
let x = a   [0]
```
and
```
let x = a
[0]
```
Ideally, only the first one should be valid.

_Originally proposed by @bobbinth in https://github.com/0xPolygonMiden/air-script/issues/123#issuecomment-1428693626_

**Comment by bobbinth** [comment]
Maybe we can just add semi-colons to address this.

**Comment by bobbinth** [comment]
Largely closed by #353. The only outstanding thing is adding commas to separate arms of the `match` statement.

[sydhds](https://github.com/sydhds) will open a PR for this soon.
