### ISSUE TITLE
Improve handling of exponentiations

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-script#149]
Codegen for something like a^b where both a and b are constants results in something like:

```
(E::from(a_u64)).exp(E::PositiveInteger::from(b_u64))
```
Ideally it should be something like:

```
E::from(a_u64.pow(b))
```
and eventually this should be further optimized to just be
```
E::from(8_u64)
```
where a = 2 and b = 3.

This will involve making changes to both IR and codegen where evaluating the exponent before generating code could be an optimization pass.

_Originally proposed by @bobbinth in https://github.com/0xPolygonMiden/air-script/pull/136#discussion_r1107759302_

**Comment by jan-ferdinand** [comment]
Not that I have any knowledge of the current status nor any say in this, but [constant folding](https://en.wikipedia.org/wiki/Constant_folding) sounds like a good idea in general, not just for exponentiation.

**Comment by tohrnii** [comment]
@jan-ferdinand Thanks for pointing it out. Agreed, constant folding is something we plan to do as part of adding some optimization passes to the IR in the future.

**Comment by bobbinth** [comment]
Superseded by #333.
