### ISSUE TITLE
Add end-to-end testing of full transpilation pipeline

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/air-script#16]
We should set up a structure for testing full files and add a few tests of full air files for v0.1 - some simple, and some that use the full v0.1 specification (e.g. `system.air` and `binary.air` that @tohrnii previously defined)

We may want to consider something like [expect_test](https://docs.rs/expect-test/latest/expect_test/) for this

**Comment by tohrnii** [comment]
@grjte Can this issue be closed?

**Comment by grjte** [comment]
Closed by #42
