### ISSUE TITLE
List comprehension for lists of variable-size

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/air-script#163]
Support for regular list comprehension over lists of static length is addressed by #87 which applies to transition constraints (and maybe boundary constraints)

Once variable-length public inputs are supported (#143), we will need to support list comprehension for lists of variable size - this applies only to boundary constraints as variable-sized lists are possible only for public inputs.

**Comment by bobbinth** [comment]
As described in https://github.com/0xPolygonMiden/air-script/issues/143#issuecomment-1563654091, variable-length public inputs would be a special case which we might want to handle differently.

Outside of variable-size public inputs, I'm not sure we need to handle comprehensions of variable size - so, I'll close this issue. If the need arises in the future, we can re-open it.
