### ISSUE TITLE
masm codegen: identify procedures/interface for use by STARK verifier

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/air-script#166]
We need to clarify the design for the STARK verifier and use that to identify the interface (i.e. what stack and memory should look like) and the procedures that need to be generated in Miden assembly. From there, we can break the Miden assembly codegen down into separate issues.

**Comment by hackaugusto** [comment]
reference: there is an initial proposal at https://github.com/0xPolygonMiden/air-script/issues/164#issuecomment-1454224293
