### ISSUE TITLE
write MidenVM constraints for the range checker (excludes multiset check constraints)

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-script#178]
The constraints for the range checker are described [here](https://0xpolygonmiden.github.io/miden-vm/design/range.html#execution-trace-constraints) and implemented in Rust [here](https://github.com/0xPolygonMiden/miden-vm/blob/main/air/src/range.rs).

The following constraints related to multiset checks should be excluded from this issue:

- 8-bit range checks table
- range checker communication bus

**Comment by grjte** [comment]
closed by #184
