### ISSUE TITLE
Add support for ConstraintComprehension

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-script#187]
We should add support for statements like these:

```
enf a = a^2 for a in a_limb
```
OR
```
enf x = y for (x, y) in (s1, s2)
```
We could handle this similar to how we handle list comprehension where we unfold this into multiple constraints in the IR for each `a` in `a_limb` etc.

**Comment by bobbinth** [comment]
Closing as this seems to be already supported.
