### ISSUE TITLE
Enforce selectors are binary

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-script#219]
Currently we don't enforce that the selectors used are binary. It would be good to figure out a way to enforce they are binary or throw a warning if users don't enforce that selectors are binary.

**Comment by bobbinth** [comment]
Yes, this would be great to have but probably not for v0.3. The way to do this could be to add type information to columns/variables in the IR.

**Comment by bobbinth** [comment]
Superseded by #334.
