### ISSUE TITLE
Refactor constraint comprehension

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-script#236]
1. Combine `Constraint` and `ConstraintComprehension` variants for both integrity and boundary constraints.
```
pub enum IntegrityStmt {
    Constraint(ConstraintType, Option<ConstraintComprehensionContext>, Option<Expression>),
    Variable(Variable),
}
```

2. Modify the ordering of the syntax for constraint comprehension with selectors. E.g.
```
enf x = a + b for x in c when s[0] & s[1]
```

_Originally proposed by @grjte in https://github.com/0xPolygonMiden/air-script/pull/189_

**Comment by grjte** [comment]
Closed by #269
