### ISSUE TITLE
Throw error when `trace_columns` do not contain `main` declaration

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/air-script#29]
Currently it's possible to declare a trace columns source section without declaring the shape of the main execution trace. This shouldn't be possible. A new test should be added when it is fixed.

This is wrong but currently transpiles without error
```
trace_columns:
    aux: [a, b]
```

**Comment by grjte** [comment]
We should also throw an error when the trace_columns source section is not defined. I don't think this case is currently handled. It probably belongs in the `ir`

**Comment by tohrnii** [comment]
Closed by #52.
