### ISSUE TITLE
Refactor comprehension

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-script#292]
> I find the method names a bit confusing, and the comprehension handling feels a bit complex in comparison to how a lot of the rest of the IR is handled now. I don't think we should make a change now, but I think it might be worth revisiting all of the comprehension handling to see if there's a way we can simplify/clarify a bit. I didn't make any significant updates to these sections during the recent refactors, so there may be opportunities for improvement.

_Originally posted by @grjte in https://github.com/0xPolygonMiden/air-script/pull/287#pullrequestreview-1410522765_

**Comment by bobbinth** [comment]
Closing this as I believe this is not obsolete as things changed quite a bit with the modularity refactoring.
