### ISSUE TITLE
Clarify syntax for core language in example constraints file

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/air-script#3]
Once we implement a core subset of everything discussed [here](https://github.com/maticnetwork/miden/discussions/254), we will be able to define the majority of Miden VM's constraints using this DSL.

To identify & settle questions for this first core version, it's useful to see what our constraints actually look like in this language for a reasonably self-contained set of constraints.

@tohrnii has defined the constraints for Miden's bitwise chiplet  [here](https://gist.github.com/tohrnii/88e8c933b08e3166b3bf1fb7cd276419) according to the previously referenced discussion

Let's discuss/adjust & agree on any questions related to this file, then possibly expand a bit to match the scope of the first milestone for this project. (We will want to include `boundary_constraints` and possibly the `aux` `trace_columns` and `use` imports as well)

This will give us a guiding example as we move forward and ensure that the language is clear, consistent, and usable.

**Comment by grjte** [comment]
I think @tohrnii's definition of the bitwise chiplet constraints provides a good example to work from!

Things to settle before moving forward:
1. Comment syntax - I don't think this was ever discussed, but maybe we should use python-style comments with "#", since so much of this is python-esque and that's also what we use for Miden Assembly
2. I strongly prefer "enforce" to "enf". It's much more explicit and readable by someone who doesn't know the language, and since this is a DSL that no one will know I think it would be better to try to have it be as readable as possible without referring to docs.
3. Range handling - the file above does this in 2 different ways with `for i in 0..4` and `for i in range(0, 4)`. We should be consistent, and I would probably lean towards `range(x,y)` although my preference is less strong here.
4. We will need a way to declare auxiliary columns, so I think the version of the `state` handling in this gist won't work. I think we should use the `trace_columns` and `periodic_columns` groupings described here: https://github.com/maticnetwork/miden/discussions/254#discussioncomment-3275932 (alternatively we could use the `declare` option described there, but I prefer the `trace_columns` and `periodic_columns` sections)

**Comment by bobbinth** [comment]
Some thoughts from me:

1. Comment syntax - yes, agreed!
2. `enforce` vs. `enf` - I have a slight preference for `enf`. My main concern with using `enforce` is not so much verbosity but that we'd need to use full name for most other keywords - e.g., `function` vs. `fn`, `define` vs `def`, `evaluator` vs. `ev` etc.
3. I have a slight preference for `0..4` syntax for ranges - mostly because I think it is cleaner.
4. I think the structure of the file could be similar to what I described [here](https://github.com/maticnetwork/miden/discussions/254#discussioncomment-3589612) - i.e., using `trace_columns`, `periodic_columns`, `transition_constraints` etc.

**Comment by grjte** [comment]
The core has been clarified during v0.1 and outlined in the docs completed in #36. I think the syntax for each subsequent version should be defined in version-specific discussions, so I'm closing this issue.
