### ISSUE TITLE
Throw error when `public_inputs` is empty or omitted

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/air-script#30]
At least one public input should be required, so this source section should be required and non-empty.

We should add tests and errors for the following cases:
- [ ]  no public_inputs section - this error & test should probably happen in the `ir`
- [x] public_inputs section is empty - this error & test can happen in the `parser`

**Comment by grjte** [comment]
The second item was addressed in #32

**Comment by tohrnii** [comment]
Closed by #32 and #52.
