### ISSUE TITLE
Throw error when boundary_constraints is empty or omitted

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/air-script#44]
We should make it a requirement to have boundary constraints. When this is updated, the mdbook docs section about `boundary_constraints` should also be updated.

- [ ] update in the parser: boundary_constraints sections should have at least one boundary constraint
- [ ] update in the IR: at least one boundary_constraints source section should be defined
- [ ] update in mdbook docs as noted here: https://github.com/0xPolygonMiden/air-dsl/pull/36#discussion_r1006185096

**Comment by tohrnii** [comment]
Closed by #52.
