### ISSUE TITLE
Throw error when transition_constraints is empty or omitted

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/air-script#45]
We should make it a requirement to have transition constraints. When this is updated, the mdbook docs section about `transition_constraints` should also be updated.

- [ ] update in the parser: transition_constraints sections should have at least one transition constraint
- [ ] update in the IR: at least one transition_constraints source section should be defined
- [ ] update in mdbook docs as noted here: https://github.com/0xPolygonMiden/air-dsl/pull/36#discussion_r1006190244

**Comment by tohrnii** [comment]
Closed by #52.
