### ISSUE TITLE
Throw error for boundary constraints using `$rand` against main trace

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/air-script#46]
The use of `$rand` random values by boundary constraints should be limited to auxiliary constraints and therefore to boundary constraints which are against columns from the auxiliary trace.

We need to throw an error if `$rand` is used in boundary constraints defined against main trace columns. This should be handled in the IR.

For example, this should be an error:

```
...
trace_columns:
    main: [a, b]
...
boundary_constraints:
    enf b.first = a + $rand[0]
...
```

See:
https://github.com/0xPolygonMiden/air-dsl/pull/36#discussion_r1006186112
https://github.com/0xPolygonMiden/air-dsl/pull/36#discussion_r1006188516

**Comment by tohrnii** [comment]
Closed by #137.
