### ISSUE TITLE
Consider adding sections for random values and validity constraints

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/air-script#53]
For some backends it may be useful to have additional sections defined which could make constraint descriptions cleaner.

### Random values
One such section could be `random_values`. This section would enable naming/grouping of random values similar to how trace columns section allows for trace columns. The syntax for this section could look as follows:
```
random_values:
    rand: [15]
```
The above specifies that there should be 15 random available for use in auxiliary trace constraints, and that these random values will be available under variable `$rand`.

Similar to trace columns, we could name various values as follows:
```
random_values:
    rand: [a, b]
```
The above specifies that `a` and `b` names could be used to refer to specific random values, and also that `$rand` variable could be used to refer to the entire vector.

### Validity constraints
Another such section could be `validity_constraints`. These constraints would be similar to transition constraints, with the only exception that they would work only with the current row of the trace. For example:
```
trace_columns:
    main: [a, b, c]

validity_constraints:
    enf a^2 - a = 0
```

Another option is to determine whether a constraint is a validity constraint or a transition constraint automatically and then we don't need an additional section. Though, we will need to rename `transition_constraints` section into something more general.

**Comment by bobbinth** [comment]
One option for a common name for transition and validity constraints is `consistency_constraints` - though, I wonder if we could come up with anything better.

**Comment by bobbinth** [comment]
Maybe `integrity_constraints` is a bit better.

**Comment by tohrnii** [comment]
Moved to #84 and #86.
