### ISSUE TITLE
Replace inlined constants with named constants

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-script#99]
> In the future, it would be cool to replace all inline constants with named constants. Could be one of optimization passes.

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/air-script/pull/95#discussion_r1041381877_

**Comment by bobbinth** [comment]
Closing this as now I think the opposite might be a better option (i.e., replacing all named constants with inlined constants).
